image: python:3.8

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - test
  - build

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  stage: test
  script:
    - python -m pip install .[dev]
    - python -m unittest discover -s tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

lint:
  stage: test
  script:
    - python -m pip install flake8
    - flake8
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

build_artifacts:
  stage: build
  script:
    - python -m pip install .[release]
    - python -m build
    - cd docs
    - make html
    - cd build/html
    - zip -r ../../doc_html.zip *
  artifacts:
    paths:
      - dist/*.whl
      - docs/doc_html.zip
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
